In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv(
    "../data/raw/Telco-Customer-Churn.csv"
)

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

In [5]:
df["TotalCharges"] = df["TotalCharges"].fillna(
    df["TotalCharges"].median()
)

In [6]:
df["TotalCharges"].isnull().sum()

np.int64(0)

In [7]:
df["TotalCharges"].dtype

dtype('float64')

In [11]:
print(df.columns.tolist())

['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

In [12]:
df["Churn"] = df["Churn"].map(
    {
        "No":0,
        "Yes":1
    }
)

In [13]:
df["Churn"].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [14]:
X = df.drop(
    "Churn",
    axis=1
)

y = df["Churn"]

In [15]:
print(X.shape)
print(y.shape)

(7043, 19)
(7043,)

In [16]:
categorical_cols = X.select_dtypes(
    include="object"
).columns

categorical_cols

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='object')

In [17]:
X = pd.get_dummies(
    X,
    drop_first=True
)

In [18]:
X.shape

(7043, 30)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [21]:
print(X_train.shape)
print(X_test.shape)

(5634, 30)
(1409, 30)

### Scale Numerical Features

In [22]:
numeric_cols = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

In [23]:
scaler = StandardScaler()

In [24]:
X_train[numeric_cols] = scaler.fit_transform(
    X_train[numeric_cols]
)

Transform Test Data

In [25]:
X_test[numeric_cols] = scaler.transform(
    X_test[numeric_cols]
)

In [26]:
X_train[numeric_cols].head()

        tenure  MonthlyCharges  TotalCharges
3738  0.102371       -0.521976     -0.263289
3151 -0.711743        0.337478     -0.504814
4860 -0.793155       -0.809013     -0.751213
3867 -0.263980        0.284384     -0.173699
3810 -1.281624       -0.676279     -0.990851

In [28]:
import pickle

with open(
    "../models/scaler.pkl",
    "wb"
) as file:
    
    pickle.dump(
        scaler,
        file
    )

In [29]:
import os

os.listdir("../models")

['scaler.pkl', '.gitkeep']